#!/bin/bash
# Push secrets from packages/cms-admin/.env.local to deployment targets.
#
# Usage:
#   ./scripts/push-secrets.sh            # push to all configured targets
#   ./scripts/push-secrets.sh fly        # Fly.io only
#   ./scripts/push-secrets.sh docker     # Docker .env.secrets only
#   ./scripts/push-secrets.sh github     # GitHub Actions secrets only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/packages/cms-admin/.env.local"
DOCKER_SECRETS_FILE="$ROOT_DIR/.env.secrets"

FLY_APP="webhouse-cms"
GH_REPO="webhousecode/cms-engine"

# ── Secrets to push (picked from .env.local) ──────────────────────────────
# Only these keys are considered secrets — dev-only vars stay local.
SECRET_KEYS=(
  CMS_JWT_SECRET
)
# Note: AI API keys (ANTHROPIC_API_KEY etc.) are site-specific and stored in
# {projectDir}/_data/ai-config.json via the Admin UI (Settings → AI).

# ── Parse target ──────────────────────────────────────────────────────────
TARGET="${1:-all}"

# ── Read secrets from .env.local ──────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo "✗ Not found: $ENV_FILE"
  exit 1
fi

declare -A SECRETS
for key in "${SECRET_KEYS[@]}"; do
  # Match KEY=VALUE (ignores comments, export prefix)
  value="$(grep -E "^(export )?${key}=" "$ENV_FILE" | sed "s/^[^=]*=//" | tr -d "'\"")"
  if [[ -z "$value" ]]; then
    echo "⚠  $key is not set in .env.local — skipping"
  else
    SECRETS[$key]="$value"
  fi
done

if [[ ${#SECRETS[@]} -eq 0 ]]; then
  echo "✗ No secrets found to push. Set CMS_JWT_SECRET and ANTHROPIC_API_KEY in .env.local first."
  exit 1
fi

echo "Secrets found: ${!SECRETS[*]}"
echo ""

# ── Push to Fly.io ────────────────────────────────────────────────────────
push_fly() {
  echo "→ Fly.io ($FLY_APP)"
  if ! command -v fly &>/dev/null; then
    echo "  ✗ fly CLI not found — install from https://fly.io/docs/hands-on/install-flyctl/"
    return 1
  fi

  args=()
  for key in "${!SECRETS[@]}"; do
    args+=("${key}=${SECRETS[$key]}")
  done

  fly secrets set "${args[@]}" --app "$FLY_APP"
  echo "  ✓ Fly.io secrets set"
}

# ── Push to Docker (.env.secrets) ─────────────────────────────────────────
push_docker() {
  echo "→ Docker ($DOCKER_SECRETS_FILE)"
  # Write / overwrite the secrets file
  {
    echo "# Auto-generated by push-secrets.sh — do not edit manually"
    echo "# Loaded by docker-compose.yml as env_file for cms-admin"
    for key in "${!SECRETS[@]}"; do
      echo "${key}=${SECRETS[$key]}"
    done
  } > "$DOCKER_SECRETS_FILE"
  chmod 600 "$DOCKER_SECRETS_FILE"
  echo "  ✓ Written: $DOCKER_SECRETS_FILE"
  echo "  Restart containers to apply: docker compose -f $ROOT_DIR/docker-compose.yml up -d cms-admin"
}

# ── Push to GitHub Actions ────────────────────────────────────────────────
push_github() {
  echo "→ GitHub Actions ($GH_REPO)"
  if ! command -v gh &>/dev/null; then
    echo "  ✗ gh CLI not found — install from https://cli.github.com/"
    return 1
  fi

  for key in "${!SECRETS[@]}"; do
    gh secret set "$key" --body "${SECRETS[$key]}" --repo "$GH_REPO"
    echo "  ✓ $key"
  done
}

# ── Dispatch ──────────────────────────────────────────────────────────────
case "$TARGET" in
  fly)
    push_fly
    ;;
  docker)
    push_docker
    ;;
  github)
    push_github
    ;;
  all)
    push_fly    || echo "  ! Fly.io failed — continuing"
    echo ""
    push_docker || echo "  ! Docker failed — continuing"
    echo ""
    push_github || echo "  ! GitHub failed — continuing"
    ;;
  *)
    echo "Unknown target: $TARGET"
    echo "Usage: $0 [fly|docker|github|all]"
    exit 1
    ;;
esac

echo ""
echo "Done."
